# Generated by Django 4.1.1 on 2022-09-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_ancora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancora',
            old_name='valor_cpf_cnpj',
            new_name='cpf_cnpj',
        ),
    ]
