# Generated by Django 4.1.1 on 2022-09-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('valor_cpf_cnpj', models.CharField(max_length=18)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cultura1', models.CharField(max_length=30)),
                ('area_1', models.IntegerField()),
                ('cultura2', models.CharField(max_length=30)),
                ('area_2', models.IntegerField()),
            ],
        ),
    ]
