# Generated by Django 4.1.1 on 2022-09-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_produtor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtor',
            old_name='area_1',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='produtor',
            old_name='cultura1',
            new_name='cultura',
        ),
        migrations.RemoveField(
            model_name='produtor',
            name='area_2',
        ),
        migrations.RemoveField(
            model_name='produtor',
            name='cultura2',
        ),
    ]
