# Generated by Django 4.1.1 on 2022-09-13 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_produtor', '0003_remove_produtor_area_remove_produtor_cultura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtor',
            name='area1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12000, 'Área Máxima Permitida é de 12mil hectares'), django.core.validators.MinValueValidator(1, 'Área Mínima Permitida é de 1 hectare')]),
        ),
        migrations.AddField(
            model_name='produtor',
            name='area2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12000, 'Área Máxima Permitida é de 12mil hectares'), django.core.validators.MinValueValidator(1, 'Área Mínima Permitida é de 1 hectare')]),
        ),
        migrations.AddField(
            model_name='produtor',
            name='area3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12000, 'Área Máxima Permitida é de 12mil hectares'), django.core.validators.MinValueValidator(1, 'Área Mínima Permitida é de 1 hectare')]),
        ),
        migrations.AddField(
            model_name='produtor',
            name='area4',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12000, 'Área Máxima Permitida é de 12mil hectares'), django.core.validators.MinValueValidator(1, 'Área Mínima Permitida é de 1 hectare')]),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cultura1',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('café', 'Café'), ('algodao', 'Algodao')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cultura2',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('café', 'Café'), ('algodao', 'Algodao')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cultura3',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('café', 'Café'), ('algodao', 'Algodao')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cultura4',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('café', 'Café'), ('algodao', 'Algodao')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='estado',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], default=None, max_length=2),
        ),
        migrations.DeleteModel(
            name='ProdutorCultura',
        ),
    ]
