# Generated by Django 4.1.1 on 2022-09-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_produtor', '0006_alter_produtor_cultura1_alter_produtor_cultura2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtor',
            old_name='valor_cpf_cnpj',
            new_name='cpf_cnpj',
        ),
    ]
